name: toni_app
description: Toni smart camera mobile application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State management
  provider: ^6.1.1
  
  # Network
  http: ^1.1.0
  socket_io_client: ^2.0.3+1
  
  # BLE
  flutter_blue_plus: ^1.30.0
  
  # Audio
  speech_to_text: ^6.6.0
  flutter_tts: ^4.0.2
  record: ^5.0.4
  sound_stream: ^0.3.0
  sherpa_onnx: ^1.9.0
  audioplayers: ^5.2.1
  permission_handler: ^11.0.1
  
  # Image processing
  image: ^4.1.3
  
  # Utilities
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  image_gallery_saver: ^2.0.3
  
  # Local Database
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  sqflite: ^2.3.0
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - ../assets/model/

